services:
  db:
    image: postgres:16.3
    container_name: postgres-tp
    environment:
      POSTGRES_DB: phoneServiceDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  backend: